### ISSUE TITLE
make links active, which starts with "www" (maybe similar to ticket #226 at opening-hours/opening_hours.js)

### ISSUE THREAD

**Issue by my-na-me** [opening-hours/opening_hours_map#59]
Hi all,

I discovered links which starts with "www" (without http or https) for `website=www.xxx.xxx` and `contact:website=www.xxx.xxx` are **not** working.

An example node you can find be running this query:
http://overpass-turbo.eu/s/qbb
http://www.openstreetmap.org/node/2380903579

Viewing the example node using http://openingh.openstreetmap.de looks like:
http://openingh.openstreetmap.de/?zoom=18&lat=50.73593&lon=7.09889&layers=B0T&filter=none&tags=opening_hours
See also picture below: [1]

Maybe this behavior is similar to ticket: 
https://github.com/opening-hours/opening_hours.js/issues/226

Thank you & regards
MN

[1]
![image](https://user-images.githubusercontent.com/27923772/27842165-b7cd7202-6107-11e7-9654-a21ffe239bfc.png)

**Comment by ypid** [comment]
Thanks for reporting. Can be done. One could argue that the input data is wrong because they are specified to be URLs.

https://wiki.openstreetmap.org/wiki/Key:website
https://wiki.openstreetmap.org/wiki/Key:contact

When the URL scheme is missing it would need to be guessed. http would be the legacy default and https is becoming the new default. For compatibility, we would need to stick with http for now.

**Comment by my-na-me** [comment]
Thanks for checking.
You are right, input data don't have syntax as specified.
So I can change, if I want, osm data, to get links working.
From my side, you can close this issue.

**Comment by ypid** [comment]
Doing that then :) Thanks for the feedback.
